github:
    is_project_page: false
    
theme: jekyll-theme-cayman
name: Carmel Freeman, Musician
title: null
profile_pic: images/carmeldune.JPG

docs:
-
  title: bio
  url: pages/bio.html
-
  title: audio/visual
  url: pages/av.html
-
  title: lessons
  url: pages/lessons.html
-
  title: contact
  url: pages/contact.html

